name: Blog

on:
  push:
    branches:
      - main
  issues:
    types:
      [
        opened,
        closed,
        edited,
        milestoned,
        labeled,
        unlabeled,
        reopened,
        demilestoned,
      ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: Yidadaa/Issue-Blog-With-Github-Action
          ref: v2
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget https://raw.githubusercontent.com/Yidadaa/Yidadaa.github.io/master/.github/workflows/resume.json -O ./config/resume.json
          wget https://raw.githubusercontent.com/Yidadaa/Yidadaa.github.io/master/.github/workflows/custom.js -O ./config/custom.js
          npm install vuepress
          npm install
          npm run action
          npm run build
          npm run deploy
